### ISSUE TITLE
Voice memos OWA

### ISSUE THREAD

**Issue by AntoineTurmel** [Mozilla-Student-Projects/Projects-Tracker#20]
This project is part of the ongoing Open Web Applications effort led by http://www.mozilla.org to liberate users from the closed, locked apps and app stores. Open Web Applications bring the power and the freedom of the web to desktops, tablets, cellphones.

I would like to be able to record voice memos, using either my phone, or my microphone on desktop.
Memos would be store in localStorage or as files with date, and maybe some text notes associated.

**Comment by aurelien** [comment]
Hello, I would like to take this project but I have some questions. Is there a WebAPI that uses audio recording? Have you an example that uses the audio recording in a Webapp? I also wanted to know if there Framework to build applications on Firefox OS? Otherwise I can use Jquery Mobile to design the Voice memos OWA ? 
Thanks 

Best Regards
Aurélien

**Comment by AntoineTurmel** [comment]
Using getUserMedia

https://developer.mozilla.org/en-US/docs/WebRTC/navigator.getUserMedia

**Comment by RiValZz** [comment]
Ok thanks. 

We will take this project. 
Are you agree to be our External responsable ?

**Comment by AntoineTurmel** [comment]
@RiValZz
Why not, are you from Evry (CoMETE)  ?

**Comment by RiValZz** [comment]
Yes we are from Evry in Master 2 MIAGE.

Can you assign us to this project me and Aurelien GEANT (aurelien) as contributors ?

Here is the link of our project : https://github.com/aurelien/Voice-Memos-OWA

**Comment by AntoineTurmel** [comment]
@RiValZz 
I can't assign you on this issue but it's fine if you started up your own repository.

@Yoric any idea ?

**Comment by Yoric** [comment]
Marked it assigned. @GeekShadow, I'll count on you to remember to whom it is assigned :)

**Comment by RiValZz** [comment]
bonjour,

Nous travaillons actuellemnt sur l'elaboration d'un enregistreur audio sur Firefox OS dans le cadre du projet CoMETE. Nous rencontrons un soucis pour l'enregistrement audio. En effet, nous avons implementé getUserMedia, on arrive a capturé l'audio cependant nous n'avons pas trouver de solution en ce qui concerne l'enregistrement du MediaStream.

Nous avons essayé d'utiliser MediaStreamRecorder de W3C mais apparement Nightly ne l'a pas encore implémenté.

Nous avons aussi essayé d'utiliser windows.webkitaudiocontext() mais n'est pas compatible avec FireFox.

Avez vous une idée ?

**Comment by AntoineTurmel** [comment]
@RiValZz je t'invite à demander de l'aide sur le channel #devfr sur irc.mozilla.org :)
- https://hacks.mozilla.org/2012/07/getusermedia-is-ready-to-roll/

**Comment by RiValZz** [comment]
Hello,

We spoke with some dev from the IRC #devfr, and they said that the record compatibility with Firefox is not possible yet. They said that it will be able to work in 6 month nearly.

We will comit on the github of the project what we have done in order to help people who will want to continue this project in the future. (link of the github : https://github.com/aurelien/Voice-Memos-OWA)

We decide to continue our project SMIL with Websocket for the CoMETE project..

Best regards,
Julian DEMAREST & Aurelien GEANT.

**Comment by AntoineTurmel** [comment]
@RiValZz
it's not possible yet on public version but on nightly it's possible.

**Comment by RiValZz** [comment]
Yes, getUserMedia work on Nightly but mediaStreamRecord don't work on Nightly.
It is "padenot" who said us this.

**Comment by AntoineTurmel** [comment]
@RiValZz ok so feel free to work on another project then :)

**Comment by AntoineTurmel** [comment]
Done, several apps do that on the marketplace:
https://marketplace.firefox.com/app/dictaphone
