### ISSUE TITLE
Add a file picker to FirefoxOS

### ISSUE THREAD

**Issue by Yoric** [Mozilla-Student-Projects/Projects-Tracker#56]
At the time of its first release, Firefox OS will come without a file picker, i.e. applications will not be able to prompt the user to choose a file. However, it is quite possible to implement a file picker using existing APIs.

The objective of this project is to implement in JavaScript, HTML and CSS a file picker, using:
- the [Device Storage API](https://wiki.mozilla.org/WebAPI/DeviceStorageAPI) to access the files;
- [Web Activities](https://wiki.mozilla.org/WebAPI/WebActivities) to communicate with other applications.

Once complete, the application will be submitted to the Firefox Marketplace and will be made available to users across the world.

**Comment by Yoric** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=801635 for a discussion on the API of this file picker.

**Comment by amodnn** [comment]
Hello,
I am interested to contribute in the project. I selected it since I had worked on the concept earlier at https://github.com/amodnn/pickApplication where I had written the code for the requesting application. Also I had implemented export feature at https://github.com/amodnn/editOnTheGo/blob/gh-pages/js/export.js where I had written the code for the rendering application.

When discussed on irc, Yoric said he is too busy to mentor the project. So I would be highly obliged if anyone is interested to be a mentor. I will also drop a request message at #gaia in irc.
Thanks !

**Comment by amodnn** [comment]
the repository : https://github.com/amodnn/filePicker/tree/gh-pages
it is hosted at : http://amodnn.github.io/filePicker

the project will function only in Firefox OS Simulator.

**Comment by amodnn** [comment]
kaze will be mentoring the project but he is busy till August. Till then i would be contributing to it,

**Comment by Mte90** [comment]
any news about this?

**Comment by AntoineTurmel** [comment]
There are now severals "Explorer" apps on the marketplace and it's possible to pick files using it:
- https://marketplace.firefox.com/app/explorer
- https://marketplace.firefox.com/app/files

I assume now we want to integrate a file browser, directly to gaia no ?

**Comment by Mte90** [comment]
There is also my post on stackoverflow http://stackoverflow.com/questions/23527190/file-picker-on-firefox-os

I think that a file picker is less invasive and simple respect to file browser. 
Choose a file (sd or system) and return the name, the path and the glob (if required)

**Comment by Amanjot1507** [comment]
Is this project complete ?

If it is not, I would like to work on it! :)

**Comment by Mte90** [comment]
http://stackoverflow.com/a/25827039
A developer have written a file picker, i'm waiting a code example for try it :-)
