### ISSUE TITLE
Port Firefox Reader Mode to Firefox for Windows 8 Metro tablets

### ISSUE THREAD

**Issue by mbrubeck** [Mozilla-Student-Projects/Projects-Tracker#57]
Information about reader mode: http://lucasr.org/2012/06/21/reader-mode-in-firefox-mobile/

Information about the student project to implement Reader Mode in desktop Firefox: https://msujaws.wordpress.com/tag/reader-mode/

Documentation about the Firefox for Metro project: https://wiki.mozilla.org/Firefox/Windows_8_Integration

See also Issue #47 (port Reader Mode to Firefox OS).

**Comment by eklavyamirani** [comment]
Hi,

I would love to do this for my semester project this semester, along with a friend, so can you assign it to me?

Thanks,
Eklavya

**Comment by Yoric** [comment]
With pleasure. This bug is assigned to @eklavyamirani .

**Comment by AbhinavSingla** [comment]
I am eklavyamirani's teammate

**Comment by eklavyamirani** [comment]
Currently, getting the reader mode to work on firefox desktop.

Update so far:
Identified that indexedDB isnt working, silently failing with an unknow exception as described here : https://bugzilla.mozilla.org/show_bug.cgi?id=643318 [disabling caching for the time-being.]

Also, identified some problems with the existing WIP reader-mode patch at : https://bugzilla.mozilla.org/show_bug.cgi?id=558882
It does not work in windows due to some missing entries in source/browser/themes/winstripe/jar.mn under the aero section. [Fixed it. Reader mode icon now shows on url bar, and the about:reader page shows the reader mode toolbar.]

Reader mode on desktop firefox is now working under windows. Tested on Windows Server 2012

**Comment by eklavyamirani** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=927124
https://bugzilla.mozilla.org/show_bug.cgi?id=915272
https://bugzilla.mozilla.org/show_bug.cgi?id=920712

**Comment by AntoineTurmel** [comment]
@mbrubeck I assumed Firefox Metro was dropped, I am correct ?

**Comment by mbrubeck** [comment]
@AntoineTurmel That's correct; Metro Firefox is no longer actively in development and we are not planning to ship it as part of Firefox (though the code is still open source for anyone who wants to build or modify it themselves).  Closing this issue.
